/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/renderer/index.html',
    './src/renderer/src/**/*.{js,ts,jsx,tsx}',
    './src/renderer/src/**/*.{css,html}'
  ],
  theme: {
    extend: {
      colors: {
        'background': 'var(--bg-background, #faf8ff)',
        'surface': 'var(--bg-surface, #faf8ff)',
        'surface-dim': 'var(--surface-dim, #d2d9f4)',
        'surface-bright': 'var(--surface-bright, #faf8ff)',
        'surface-container-lowest': 'var(--surface-container-lowest, #ffffff)',
        'surface-container-low': 'var(--surface-container-low, #f2f3ff)',
        'surface-container': 'var(--surface-container, #eaedff)',
        'surface-container-high': 'var(--surface-container-high, #e2e7ff)',
        'surface-container-highest': 'var(--surface-container-highest, #dae2fd)',
        'surface-variant': 'var(--surface-variant, #dae2fd)',
        'surface-canvas': 'var(--surface-canvas, #f8fafc)',
        'surface-sidebar': 'var(--surface-sidebar, #0f172a)',
        'surface-panel': 'var(--surface-panel, #ffffff)',
        'surface-elevated': 'var(--surface-elevated, #ffffff)',
        'surface-hover': 'var(--surface-hover, #f1f5f9)',
        'on-surface': 'var(--text-on-surface, #131b2e)',
        'on-surface-variant': 'var(--text-on-surface-variant, #464555)',
        'inverse-surface': 'var(--inverse-surface, #283044)',
        'inverse-on-surface': 'var(--inverse-on-surface, #eef0ff)',
        'text-primary': 'var(--text-primary, #0f172a)',
        'text-secondary': 'var(--text-secondary, #475569)',
        'text-muted': 'var(--text-muted, #94a3b8)',
        'outline': 'var(--outline, #777587)',
        'outline-variant': 'var(--outline-variant, #c7c4d8)',
        'border-subtle': 'var(--border-subtle, #e2e8f0)',
        'border-strong': 'var(--border-strong, #cbd5e1)',
        'primary': 'var(--primary, #4f46e5)',
        'on-primary': 'var(--on-primary, #ffffff)',
        'primary-container': 'var(--primary-container, #4f46e5)',
        'on-primary-container': 'var(--on-primary-container, #dad7ff)',
        'primary-fixed': 'var(--primary-fixed, #e2dfff)',
        'primary-fixed-dim': 'var(--primary-fixed-dim, #c3c0ff)',
        'on-primary-fixed': 'var(--on-primary-fixed, #0f0069)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant, #3323cc)',
        'secondary': 'var(--secondary, #006591)',
        'on-secondary': 'var(--on-secondary, #ffffff)',
        'secondary-container': 'var(--secondary-container, #39b8fd)',
        'on-secondary-container': 'var(--on-secondary-container, #004666)',
        'secondary-fixed': 'var(--secondary-fixed, #c9e6ff)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim, #89ceff)',
        'on-secondary-fixed': 'var(--on-secondary-fixed, #001e2f)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant, #004c6e)',
        'tertiary': 'var(--tertiary, #3130c0)',
        'on-tertiary': 'var(--on-tertiary, #ffffff)',
        'tertiary-container': 'var(--tertiary-container, #4b4dd8)',
        'on-tertiary-container': 'var(--on-tertiary-container, #d9d8ff)',
        'tertiary-fixed': 'var(--tertiary-fixed, #e1e0ff)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim, #c0c1ff)',
        'error': 'var(--error, #ba1a1a)',
        'on-error': 'var(--on-error, #ffffff)',
        'error-container': 'var(--error-container, #ffdad6)',
        'on-error-container': 'var(--on-error-container, #93000a)',
        'status-success': 'var(--status-success, #10b981)',
        'status-warning': 'var(--status-warning, #f59e0b)',
        'status-error': 'var(--status-error, #ef4444)'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.375rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'gutter': '0.75rem',
        'margin': '1rem'
      },
      fontFamily: {
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'title-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'caption': ['Inter', 'sans-serif']
      },
      fontSize: {
        'caption': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '19px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-mono': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['22px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }]
      }
    }
  },
  plugins: []
}
